// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv71hz6Vy5EMJK9nlj-rNxZNokHcJp4Ag',
    appId: '1:934609788473:web:38e96628d4602e009e37e8',
    messagingSenderId: '934609788473',
    projectId: 'pandanfest',
    authDomain: 'pandanfest.firebaseapp.com',
    storageBucket: 'pandanfest.firebasestorage.app',
    measurementId: 'G-N9BPR9NJ0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5OB0a6ZIWRFplqaX6U-j_RlMPpSiKSR8',
    appId: '1:934609788473:android:ff0ad75043a4f3b19e37e8',
    messagingSenderId: '934609788473',
    projectId: 'pandanfest',
    storageBucket: 'pandanfest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8egeexXx_X9GuBH967nMSusSpeLwqcE',
    appId: '1:934609788473:ios:efc7e24db807536a9e37e8',
    messagingSenderId: '934609788473',
    projectId: 'pandanfest',
    storageBucket: 'pandanfest.firebasestorage.app',
    iosBundleId: 'com.example.pandanFest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8egeexXx_X9GuBH967nMSusSpeLwqcE',
    appId: '1:934609788473:ios:efc7e24db807536a9e37e8',
    messagingSenderId: '934609788473',
    projectId: 'pandanfest',
    storageBucket: 'pandanfest.firebasestorage.app',
    iosBundleId: 'com.example.pandanFest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv71hz6Vy5EMJK9nlj-rNxZNokHcJp4Ag',
    appId: '1:934609788473:web:2b0cb487e69bc5d79e37e8',
    messagingSenderId: '934609788473',
    projectId: 'pandanfest',
    authDomain: 'pandanfest.firebaseapp.com',
    storageBucket: 'pandanfest.firebasestorage.app',
    measurementId: 'G-KKPYLXSX1M',
  );
}
